### ISSUE TITLE
Please explain plugin usefulness

### ISSUE THREAD

**Issue by pcav** [eswright/cgdi-qgis-services#16]
The functionality described in the About seems already present in core QGIS. In particular, just loading an xml file will add all WMS and WFS services at will.
Please clarify what the plugin is actually adding.
Sorry for bothering, but we are trying hard not to duplicate functionality, so to reduce confusion for the users and administrative burden.
Thanks.

**Comment by eswright** [comment]
Apologies for the delay.  I have updated the README.md file here and within the plugin.  This is somewhat like the Greek open data plugin, but the service list is not static, being obtained from a web harvest weekly.  Currently it does not have a predefined service selection.   It will continue to evolve and we expect it to remain as experimental for some time.

**Comment by pcav** [comment]
Thanks. Could you please add the into to the about.txt as well, both in the source and in the plugins.qgis.org interface?
Thanks.

**Comment by eswright** [comment]
I've added to the plugins.qgis.org  under the about tab and description.  Where is this about.txt you speak of?

**Comment by pcav** [comment]
sorry, the about tag in `metadata.txt`

**Comment by eswright** [comment]
Done. and re-uploaded.  Can it be made public?

**Comment by pcav** [comment]
Done
