### ISSUE TITLE
Impossible to use with high resolution monitors

### ISSUE THREAD

**Issue by stuskier** [eswright/cgdi-qgis-services#23]
At QGIS 3.6.1, the Canadian Web Services plugin window cannot be resized in any direction.  Thus, the text inside the window is unreadable because it is crammed into too small a space.  Additionally, columns within the window cannot be stretched.  Here's a screenshot, this is the only window size available; it is impossible to see which service to click because not enough text is viewable.  Using a MS Surface Book with 3,000 x 2,000 pixel monitor, Windows 10.  Thanks!

![Capture](https://user-images.githubusercontent.com/12805900/55998121-cc4a6c00-5c71-11e9-922e-273c56fa6584.PNG)

**To Reproduce**
1. Go to QGIS 3.6.1
2. Click on 'web', drop down to 'Canadian Web Services' > Load Canadian Web Services
3. See error

**Expected behavior**
When opened, the CWS window should be re-sizeable, and interior columns expandable.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by eswright** [comment]
Thanks.  We are trying to find some resources to direct to this project.  Please keep any other issues coming, and potential features/enhancements and hopefully we can get some forks going.

**Comment by roya0045** [comment]
Greetings, the PR that I am submitting should alleviate things a little, I'm not too sure what is the best way to set the height/width of things to properly display in high dpi monitors but the ability to resize things should make things more bearable.

**Comment by roya0045** [comment]
@stuskier is the tool more usable for your now?

**Comment by stuskier** [comment]
@roya0045 Unfortunately, the problems that I described in my OP still exist, without change.

**Comment by roya0045** [comment]
@stuskier I have tried to add high dpi compensation in the code in my pending PR. But I was not sure if @eswright had updated the PR with my first patch yet. The upcoming one might help. If you want, you could also take my branch in my current PR, download the zip, make it importable in Qgis and install the plugin from the zip.

That way I would know if my pending changes are adapted to your monitor.

**Comment by stuskier** [comment]
Hi Alex,
 
Thanks for your continued efforts with this issue!  Unfortunately, I don't know how to accomplish what you proposed - branching an all that.  However, I'd be happy to make an attempt if you would be willing to guide me through the process.
 
Regards,
 
Stu Smith
 
 
-----Original Message-----

**Comment by roya0045** [comment]
Sure thing,

1.  [Go to my branch](https://github.com/roya0045/cgdi-qgis-services/tree/patch-3)
2. Click the Clone or Download button in green, select download Zip
3. In the zip you need to move the CanadianWebServices folder up to the first level (where cdgi-qgis-services-path-3 is located and remove cdgi-qgis-services-path-3) or alternatively you can unzip the whole thing and only rezip the CanadianWebSerivces folder.
4. In Qgis Plugin Manager, uninstall CanadianWebServices
5. In the plugin manager go to install from zip, and select the zip with only CanadianWebServices inside.

**Comment by roya0045** [comment]
@stuskier did you have the chance to try it out? Or maybe some of the steps described were unclear?

**Comment by roya0045** [comment]
@stuskier Mr.Wright has merged the changes, he should update the plugin soon, I would suggest you to test the plugin once it gets update to see if the changes ease your pain.

**Comment by eswright** [comment]
v1.0 should have the issue fixed.
